# Generated by Django 4.0.10 on 2026-03-04 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_procedure_practice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure', to='organization.practice'),
        ),
    ]
